version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       
      - "15672:15672"     
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"   
    volumes:
      - redis-data:/data  
    networks:
      - backend-network

  backend:
    build: .
    container_name: cinema-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - redis    
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      REDIS_URL: redis://redis:6379   
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
